### ISSUE TITLE
I'm trying to replace the RakNet in Nukkit with JRakNet, but I ran into some problems.

### ISSUE THREAD

**Issue by boybook** [JRakNet/JRakNet#102]
`Minecraft BedRock client version: 1.7.0`
`Server: Nukkit`
`JRakNet version: 2.10.7`

I tried to issue the same GameWrapper content on the server side. In both the original RakNet and JRakNet environments, the original RakNet worked correctly, but when using JRakNet, my game crashed when the server sent AvailableCommandsPacket.
When I tried to block this packet, the client could not handle the PlayStatusPacket with PLAYER_SPAWN properly. (always on the loading screen, unable to enter the game)

Is there a problem with packet splitting? Or is there something wrong with my data packet itself?

I hope you can help me solve this problem. Thank you very much!

Here is the log of raw GameWrappers and these detailed MCPE packets, which was sent from the servers in the test, hoping to find the problem.

[packetlog.txt](https://github.com/JRakNet/JRakNet/files/2566140/packetlog.txt)

**Comment by whirvis** [comment]
Could I have some source code? I don't think there is a problem with packet splitting, but I could be wrong. I would like to see the old code and the new code especially so I can see what has changed. Make sure to keep in mind as well that RakNet is the underlying protocol of Minecraft, not the actual protocol of the game. The Nukkit RakNet that was there before might have had more code integrated into the actual RakNet code than would be in JRakNet. JRakNet is made with only the RakNet protocol implemented (with some slight modifications, but trust me these are not what cause the crash) and only the Minecraft identifier implemented.

**Comment by whirvis** [comment]
Respond within 3 days or I'm closing this issue
