### ISSUE TITLE
Failed to find a usable hardware address from the network interfaces;

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#104]
Hello!
On linux host:

Server is starting but with warning:
2019-05-21, 15:24:25 [main/WARN] MacAddressUtil: Failed to find a usable hardware address from the network interfaces; using random bytes: 7d:80:01:85:77:24:70:55

**Comment by whirvis** [comment]
~~I'll look into this. It looks like a Java issue or an issue relating to another API. I don't recall any MacAddressUtil in JRakNet. It looks like an issue relating to automatic maximum transfer unit detection. If the warning bugs you, you are able to specify it via one of the RakNetServer constructors :)~~

**Comment by whirvis** [comment]
It doesnt seem to have anything to do with Java. Instead, this error comes from Netty. Are you specifying the bind address yourself or running this in a Docker container by chance?

Also, does the server still actually function (receive connections, respond to pings, etc.) while producing this message? Or does the server simply boot and not do anything afterwards?

**Comment by diclofoss** [comment]
Hello! No I have a regular host. This issue is minor for me. Everything works fine except this for now.
(system still under functional testing, performance report will be later)

**Comment by diclofoss** [comment]
I have checked Netty issue about it but it seems like it was closed in version from your dependency. But still occured.

**Comment by whirvis** [comment]
Alright, so it does seem to be a netty error. I will make sure JRakNet is using the latest version.

**Comment by diclofoss** [comment]
In the latest version 2.11.3 issue still occurs

**Comment by whirvis** [comment]
The new version has not yet built, I do not believe. The version in the POM has been updated but the code has not yet been rebuilt due to a Jenkins issue (unless you built the code yourself, in which case please tell me you did).

**Comment by diclofoss** [comment]
Does new version was build with lates version of the netty?

**Comment by whirvis** [comment]
I believe so! Also, I believe for some reason Netty might be unable to find an address due to the machine its being run on. Try specifying an IPv4 address of localhost to bind to in the constructor if the issue still occurs to see if that helps :)
