### ISSUE TITLE
[ERROR] ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected.

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#106]
14:22:50 [ERROR] ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:436)
        io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:309)
        io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1187)
        com.whirvis.jraknet.Packet.copy(Packet.java:1186)
        com.whirvis.jraknet.Packet.<init>(Packet.java:114)
        com.whirvis.jraknet.RakNetPacket.<init>(RakNetPacket.java:1154)
        com.whirvis.jraknet.protocol.message.CustomPacket.<init>(CustomPacket.java:124)
        com.whirvis.jraknet.peer.RakNetPeer.handleInternal(RakNetPeer.java:582)
        com.whirvis.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:2490)
        com.whirvis.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:154)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:748)

**Comment by whirvis** [comment]
Could I see the code you were using before this warning came up? It looks like it might have something to do with ``CustomPacket``, but I'm not entirely sure.

**Comment by diclofoss** [comment]
`/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.samp_net.voiceserver;

import com.whirvis.jraknet.Packet;
import com.whirvis.jraknet.RakNetException;
import com.whirvis.jraknet.RakNetPacket;
import com.whirvis.jraknet.identifier.Identifier;
import com.whirvis.jraknet.protocol.Reliability;
import com.whirvis.jraknet.server.RakNetServer;
import com.whirvis.jraknet.server.RakNetServerListener;
import com.whirvis.jraknet.session.InvalidChannelException;
import com.whirvis.jraknet.session.RakNetClientSession;
import java.util.List;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.samp_net.imdb.ImdbManager;
import ru.samp_net.imdb.ImdbPlayerLocation;

/**
 *
 * @author Khlupin
 */
public class VoiceServer {

    private static final Logger logger = LoggerFactory.getLogger(VoiceServer.class);

    public static void main(String args[]) throws RakNetException {

        // Create server
        RakNetServer server = new RakNetServer(6999, 999, new Identifier("Samp-net Voice server"));
        ImdbManager imdbManager = new ImdbManager();
        logger.info("Protocol Version: " + server.getProtocolVersion());
        // Add listener
        server.addListener(new RakNetServerListener() {
            @Override
            public void onClientConnect(RakNetClientSession peer) {
                logger.info("Client from address " + peer.getAddress() + " has connected to the server");
            }

            @Override
            public void onClientDisconnect(RakNetClientSession session, String reason) {
                logger.info("Player has been disconnected");
            }

            @Override
            public void handleMessage(RakNetClientSession peer, RakNetPacket packet, int channel) {
                try {
                    int code = packet.readInt();
                    switch (code) {
                        case 20: {
                            int playerid = packet.readInt();
                            Player.register(playerid, peer);
                            Packet destPacket = new Packet();
                            destPacket.writeByte((byte)135);
                            destPacket.writeInt(0);
                            peer.sendMessage(Reliability.RELIABLE_ORDERED, destPacket);
                            logger.info("New connection player with id: " + playerid);
                            break;
                        }
                        case 21: {
                            Player player = Player.get(peer);
                            if (player == null) {
                                logger.warn("Player not found on sending voice data");
                                break;
                            }
                            List<ImdbPlayerLocation> locationList = imdbManager.getLocationList(player.playerid, 30.0f);
                            for (ImdbPlayerLocation imdbPlayerLocation : locationList) {
                                Player.sendData(imdbManager, imdbPlayerLocation.getPlayerid(), packet);
                            }
                            break;
                        }
                        default:
                            logger.warn("Unknown code: " + code);
                    }

                } catch (InvalidChannelException ex) {
                    logger.error(ex.getMessage());
                    logger.error(ExceptionUtils.getStackTrace(ex));
                }
            }
        });

// Start server
        server.start();
    }
}
`

**Comment by diclofoss** [comment]
public class VoiceServer2 {

    private static final Logger logger = LoggerFactory.getLogger(VoiceServer2.class);

    public static void main(String args[]) throws RakNetException {

        // Create server
        RakNetServer server = new RakNetServer(6999, 999, new Identifier("Samp-net Voice server"));
        ImdbManager imdbManager = new ImdbManager();
        logger.info("Protocol Version: " + server.getProtocolVersion());
        // Add listener
        server.addListener(new RakNetServerListener() {
            @Override
            public void onConnect(RakNetServer server, InetSocketAddress address, ConnectionType connectionType) {
                RakNetServerListener.super.onConnect(server, address, connectionType); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void onLogin(RakNetServer server, RakNetClientPeer peer) {
                logger.info("Client from address " + peer.getAddress() + " has connected to the server");
            }

            @Override
            public void onDisconnect(RakNetServer server, InetSocketAddress address, RakNetClientPeer peer, String reason) {
                Player.disconnect(peer);
                logger.info("Player has been disconnected");
            }

            @Override
            public void handleMessage(RakNetServer server, RakNetClientPeer peer, RakNetPacket packet, int channel) {
                try {
                    int code = packet.readInt();
                    logger.info("New packet with code: " + code + " and packetId = " + packet.getId());
                    switch (code) {
                        case 20: {
                            int playerid = packet.readInt();
                            Player.register(playerid, peer);
                            Packet destPacket = new Packet();
                            destPacket.writeByte(135);
                            destPacket.writeInt(0);
                            peer.sendMessage(Reliability.RELIABLE_ORDERED, destPacket);
                            logger.info("New connection player with id: " + playerid);
                            break;
                        }
                        case 21: {
                            Player player = Player.get(peer);
                            if (player == null) {
                                logger.warn("Player not found on sending voice data");
                                break;
                            }
                            List<ImdbPlayerLocation> locationList = imdbManager.getLocationList(player.playerid, 30.0f);
                            logger.info("Locations list size: " + locationList.size());
                            for (ImdbPlayerLocation imdbPlayerLocation : locationList) {
                                Player.sendData(imdbManager, imdbPlayerLocation.getPlayerid(), packet);
                            }
                            break;
                        }
                        default:
                            logger.warn("Unknown code: " + code);
                    }
                    logger.info("Client from address " + peer.getAddress() + " sent packet with ID "
                            + packet.getId() + " on channel " + channel + " with code: " + code);

                } catch (InvalidChannelException ex) {
                    logger.error(ex.getMessage());
                    logger.error(ExceptionUtils.getStackTrace(ex));
                }
            }

        });

// Start server
        server.start();
    }

}
