### ISSUE TITLE
Packet with larger then MTU is not sent

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#115]
I can receive packet with size larger then MTU. But I can't send it

    private void send(RakNetPacket packet) {
        Packet destPacket = new Packet();
        destPacket.writeByte((byte) 135);
        destPacket.writeByte((byte) 21);
        destPacket.writeInt(packet.readInt());
        int len = packet.readInt();
        destPacket.writeInt(len);
        for (int i = 0; i < len; i++) {
            destPacket.writeByte(packet.readByte());
        }
        peer.sendMessage(Reliability.RELIABLE, destPacket);
        logger.info("Sending packet with len " + len);
    }

**Comment by diclofoss** [comment]
Due to this log message has been received on server side, but not sent to client side.

01:37:46 [INFO] VoiceServer: Code: 21
01:37:46 [INFO] Player: Sending packet with len 3102
01:37:54 [INFO] VoiceServer: PacketId: 135
01:37:54 [INFO] VoiceServer: Code: 21
01:37:54 [INFO] Player: Sending packet with len 0
01:37:59 [INFO] VoiceServer: PacketId: 135
01:37:59 [INFO] VoiceServer: Code: 21
01:37:59 [INFO] Player: Sending packet with len 6246

**Comment by whirvis** [comment]
Thank you for the report :)

**Comment by diclofoss** [comment]
Do you have any estimations to fix it? Its blocker for me

**Comment by whirvis** [comment]
I would split the packet myself and then send multiple chunks manually that are smaller than the MTU.

Id also give it a split ID and then make sure to givr an index for each split part so when everything comes in you can assemble it in order. Something like this:
1. Your universal header (one byte)
2. Something to indicate its a split packet (boolean)
3. Split ID
4. Split count
5. Split index
6. Payload length
7. Payload

**Comment by whirvis** [comment]
I'm working on fixing these as fast as I can, I really do apologize that you've found so many issues. I thank you for notifying me so I know to fix it!

**Comment by whirvis** [comment]
@diclofoss Hey, when say it doesn't send, do you mean the server receives nothing or that the client does not send it correctly? I just fixed the issue with split packets being sent incorrectly. However, they were still being *received*, they were just encoded incorrectly.

This should be fixed now that #110 is fixed.

**Comment by diclofoss** [comment]
Hello! They didn't sent at all. Lets check new version
