### ISSUE TITLE
CodeMC.org repository outdated

### ISSUE THREAD

**Issue by filfat** [JRakNet/JRakNet#122]
The latest version on codemc.org seems to be 2.9.4. Would be great if this could be updated to the latest version 👍

**Comment by Whirvis** [comment]
@filfat I am aware of this issue, I am currently awaiting for the maintainer of CodeMC to update JRakNet (as I have no power to do so). However, you are able to install the latest version to your local maven repository so you can use it like normal!

If you need detailed instructions, let me know and I will gladly help you so you can use the latest version of JRakNet with Maven normally :)

**Comment by filfat** [comment]
Hey, thanks for the update. I’m a bit new to the java world (as in I’ve been using it for about a whopping 20hrs) so I had no clue local repositories were a thing.

I’ll keep this issue open till CodeMC is updated :)

**Comment by Whirvis** [comment]
Of course :)

**Comment by Whirvis** [comment]
Issue has been fixed! Both JRakNet snapshot and releases properly build now, and releases are uploaded to the Maven Central Repository! As I speak, 2.11.5 is now available there as well :)

Once again, I sincerely apologize this issue occurred and took so long to fix. Thank you for bringing it to my attention! If you have any more issues, please let me know and I'll be glad to fix them!
