### ISSUE TITLE
Can't connect to some servers

### ISSUE THREAD

**Issue by vytskalt** [JRakNet/JRakNet#126]
There are some Minecraft servers, that I can't seem to connect to. For example, versai.pro, it is running the latest version of Pocketmine, but probably has some modifications. You can connect to it through the Minecraft client, but cannot through this library, it just says that the server is offline. The only thing I know is that the server may send an invalid MTU, and that may cause this issue.

**Comment by whirvis** [comment]
Hello! I apologize greatly for taking so long to repsond to your bug report. Could I please see the code you are using to attempt to connect to servers? If you are getting any stack traces, I would also like those as well. Thank you!

**Comment by vytskalt** [comment]
Hello, I'm using the client example provided in the README. There are no stack traces, it just says that the server is offline.

**Comment by whirvis** [comment]
I am attempting to connect to it from the latest release version of Minecraft on Windows 10, at address ``versai.pro:19132`` and I am unable to ping it or connect to it. Likewise, the ``RakNetClient`` is unable to connect to it. I tested with some other servers running the latest version of Minecraft such as ``play.nethergames.org:19132``, ``mcpe.plutonium.best:19132``, ``rushnation.net:19132``, and ``klobby.de:19132``. I was able to ping and connect to all four of these servers on both Minecraft for WIndows 10 and with the ``RakNetClient`` via the example code.

Are you sure the server isn't simply down?

**Comment by vytskalt** [comment]
Hmm, the server wasn't down when I made this issue. But I found another server which I can connect to through the Minecraft client but can't from the library: play.fallentech.io:19132

**Comment by whirvis** [comment]
Alright, thank you for creating this issue! I will look into this as soon as I can. If you find any more problems with the JRakNet API, please do not hesitate to create an issue for those as well! I deeply appreciate it :)

**Comment by kanjiman** [comment]
[19:59:22] [RakLibServer thread/NOTICE]: Refused connection from MyIpAddressHere 60155 due to incompatible RakNet protocol version (expected 10, got 9)

this seems to be the cause, as said in the pull request. You were right, you just had to check the console of the server to find out sooner lol.
