### ISSUE TITLE
Incorrect reading of ConnectionRequestAccepted

### ISSUE THREAD

**Issue by SupremeMortal** [JRakNet/JRakNet#137]
https://github.com/JRakNet/JRakNet/blob/707e9b60a69b548d521e535ab75b791f443265b9/src/main/java/com/whirvis/jraknet/protocol/login/ConnectionRequestAccepted.java#L127

This line in `ConnectionRequestAccepted` is supposed to be checking if there is more remaining than 16 bytes however `Long.SIZE` returns the amount of bits in a `Long` so it's actually checking for more than 128 bytes. Instead `Long.BYTES` should be used.

**Comment by whirvis** [comment]
Thanks for spotting this! Fixed it just now.
