### ISSUE TITLE
Client has disconnected from the server for the reason "null"

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JRakNet/JRakNet#23]
```
Client from address /192.168.43.212:19132 has connected to the server
Client from address /192.168.43.212:19132 has disconnected from the server for the reason "null"
```

Happens with both MCW10/MCPE and that happens randomly, sometimes it decides to "fuck everything" and disconnect for the reason "null", sometimes it works and doesn't disconnect for no reason.

**Comment by whirvis** [comment]
Could I see the code you are using in which this error occurs?

**Comment by MrPowerGamerBR** [comment]
@MarfGamer I doubt it would be due to my code because sometimes the user is disconnected even before the first packet is sent.

Anyway, here is the code:
```
package com.magicalpocket.network;

import java.util.ArrayList;
import java.util.List;

import com.magicalpocket.network.packets.DataPacket;
import com.magicalpocket.network.packets.LoginPacket;
import com.magicalpocket.network.packets.PlayStatusPacket;
import com.magicalpocket.network.packets.ResourcePacksInfoPacket;
import com.magicalpocket.network.packets.StartGamePacket;
import com.magicalpocket.utils.VarInt;
import com.magicalpocket.utils.Zlib;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import net.marfgamer.jraknet.RakNetPacket;
import net.marfgamer.jraknet.identifier.MCPEIdentifier;
import net.marfgamer.jraknet.protocol.Reliability;
import net.marfgamer.jraknet.server.RakNetServer;
import net.marfgamer.jraknet.server.RakNetServerListener;
import net.marfgamer.jraknet.session.RakNetClientSession;

public class RakNetNetwork {
	public void startRakNet() {
		// Create server and set listener
		RakNetServer server = new RakNetServer(19132, 10, new MCPEIdentifier("JRakNet Example Server", 100, "1.0.0", 0,
				10, System.currentTimeMillis(), "New World", "Survival"));
		server.setListener(new RakNetServerListener() {
			// Client connected
			@Override
			public void onClientConnect(RakNetClientSession session) {
				System.out.println("Client from address " + session.getAddress() + " has connected to the server");
			}

			// Client disconnected
			@Override
			public void onClientDisconnect(RakNetClientSession session, String reason) {
				System.out.println("Client from address " + session.getAddress()
				+ " has disconnected from the server for the reason \"" + reason + "\"");
			}

			// Packet received
			@Override
			public void handlePacket(RakNetClientSession session, RakNetPacket packet, int channel) {
				System.out.println("Client from address " + session.getAddress() + " sent packet with ID 0x"
						+ Integer.toHexString(packet.getId()).toUpperCase() + " on channel " + channel);

				handlePocketPacket(session, packet, -1);
			}
		});

		// Start server
		server.start();
	}

	public void handlePocketPacket(RakNetClientSession session, RakNetPacket packet, int packetId) {
		if (packetId == -1) {
			packetId = packet.readByte();
		}
		System.out.println("Pocket Packet ID: 0x" + Integer.toHexString(packetId).toUpperCase());

		if (packetId == 1) {
			LoginPacket lp = new LoginPacket();
			lp.packet = packet;
			lp.decode();

			minimalHandshake(session);

			if (true) {
				return;
			}

			System.out.println("Connected");
		}

		if (packetId == 6) {
			// Batch packet
			System.out.println("Batch packet!");
			
			byte[] data;
			byte[] packetData;
			
			{
        		int arrayLength = (int) VarInt.readUnsignedVarInt(packet);
        		System.out.println("Batch packet length: " + arrayLength);
        		packetData = packet.read(arrayLength);
			}
			try {
				data = Zlib.inflate(packetData, 64 * 1024 * 1024);
			} catch (Exception e) {
				e.printStackTrace();
				return;
			}
			
			int len = data.length;
			
			System.out.println("Length: " + len);
			
			ByteBuf bb = Unpooled.copiedBuffer(data);
	        try {
	        	List<DataPacket> packets = new ArrayList<>();
	        	System.out.println("Reader idx: " + bb.readerIndex());
	        	while (len > bb.readerIndex()) {
	        		int arrayLength = (int) VarInt.readUnsignedVarInt(bb);
	        		
	        		int packetIdX = (int) VarInt.readUnsignedVarInt(bb);

	        		byte[] packetBytes = new byte[arrayLength];
	        		bb.readerIndex(bb.readerIndex() - 1);
	        		bb.readBytes(packetBytes, 0, arrayLength);
	        		System.out.println("Packet length: " + packetBytes.length);
	        		
	        		RakNetPacket p = new RakNetPacket(packetBytes);
	        		
	        		handlePocketPacket(session, p, packetIdX);
	        		
	        		System.out.println("Packet handled successfully!");
	        		
	        		/* System.out.println("Packet (as a array) length: " + arrayLength);
	        		
	        		byte[] dataPacket = new byte[arrayLength];
	        		bb.getBytes(arrayLength, dataPacket);
	        		
	        		System.out.println("Packet length: " + dataPacket.length);
	        		
	        		RakNetPacket p = new RakNetPacket(dataPacket);
	        		
	        		handlePocketPacket(session, p);
	        		
	        		System.out.println("Packet handled successfully!"); */
	        	}
	        } catch (Exception e) {
	        	e.printStackTrace();
	        }
		}
	}

	/**
	 * Initializes a Minimal Handshake Server -> Client
	 * 
	 * If this breaks, reset your changes ASAP!
	 * 
	 * @param session
	 */
	public void minimalHandshake(RakNetClientSession session) {
		PlayStatusPacket psp = new PlayStatusPacket();
		psp.encode();
		psp.status = 0;
		session.sendMessage(Reliability.RELIABLE_ORDERED, psp.packet);

		ResourcePacksInfoPacket pspx = new ResourcePacksInfoPacket();
		pspx.encode();
		session.sendMessage(Reliability.RELIABLE_ORDERED, pspx.packet);

		StartGamePacket sgp = new StartGamePacket();
		sgp.encode();
		session.sendMessage(Reliability.RELIABLE_ORDERED, sgp.packet);

		PlayStatusPacket psp2 = new PlayStatusPacket();
		psp2.status = 3;
		psp2.encode();
		session.sendMessage(Reliability.RELIABLE_ORDERED, psp2.packet);
	}
}
```

And sometimes the code does work without any issues (the client connects and joins the server) but sometimes the client gets disconnected randomly. (most of the times it gets disconnected until the last PlayStatusPacket is sent, but almost every time it gets disconnected even before the server receives any packet from the client!)

As you can see in the log I shown above, the client is disconnected after the "System.out.println("Client from address " + session.getAddress() + " sent packet with ID 0x"
						+ Integer.toHexString(packet.getId()).toUpperCase() + " on channel " + channel);" code but before the "System.out.println("Pocket Packet ID: 0x" + Integer.toHexString(packetId).toUpperCase());", that's why it is strange, nothing happens between those two things except logging (and getting the PE packet ID)

But what's even more stranger is that the code sometimes works, and sometimes it doesn't.

**Comment by whirvis** [comment]
I see, it probably has something to do with synchronization in the code (It could even be something with a HashMap being unsynchronized between some threads). I will look into this tonight :)

Edit: There is also the possibility that a NullPointerException occurring somewhere and so the reason being print out is literally just "null"

**Comment by whirvis** [comment]
Ok so I managed to get the error you are receiving, and I was correct. It is a NullPointerException but I am unable to reproduce it after the first time. :/ I will try my best

**Comment by whirvis** [comment]
Update: I have found the source of the error. Apparently when a CustomPacket is received, the server checks if the session's address can be found before obtaining the session from the HashMap by it's address. Apparently, even though the value is null (Which ConcurrentHashMaps do not allow), it returns true. So, since the value is null Java throws a NullPointerException because there is not session to call the method.

**Comment by whirvis** [comment]
The changes did not fix this issue, sadly.

**Comment by robotman3000** [comment]
@MrPowerGamerBR A quick, out of place question. What library provides the com.magicalpocket.network.packets.* classes in your code snip-it?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 I made those classes myself ;)

Here is one of them: (I now that they are confusing, I made those classes just for fun to see if I could connect a MCPE client to a MCPE server (in this case, JRakNet))

```
package com.magicalpocket.network.packets;

import java.io.IOException;

import com.magicalpocket.utils.BinaryUtils;
import com.magicalpocket.utils.VarInt;

import net.marfgamer.jraknet.RakNetPacket;

public class StartGamePacket extends DataPacket {
	public int status;
	
	@Override
	public void decode() {

	}

	@Override
	public void encode() {
		RakNetPacket rnp = new RakNetPacket(0xFE);
		try {
			rnp.getDataOutput().writeByte(0x0c);
			VarInt.writeVarLong(rnp, 0L); // entity ID
			VarInt.writeVarLong(rnp, 0L); // runtime ID

			// position
			rnp.write(BinaryUtils.writeLFloat(0));
			rnp.write(BinaryUtils.writeLFloat(70));
			rnp.write(BinaryUtils.writeLFloat(0));

			// yaw
			rnp.write(BinaryUtils.writeLFloat(0));
			// pitch
			rnp.write(BinaryUtils.writeLFloat(0));
			
			VarInt.writeVarInt(rnp, -1); // seed
			VarInt.writeVarInt(rnp, 1); // dimension
			VarInt.writeVarInt(rnp, 1); // generator
			VarInt.writeVarInt(rnp, 1); // World Gamemode
			VarInt.writeVarInt(rnp, 1); // Difficulty
			
			// spawn pos
			VarInt.writeVarInt(rnp, 0);
			VarInt.writeUnsignedVarInt(rnp, 70);
			VarInt.writeVarInt(rnp, 0);
			
			// loaded in creative
			rnp.writeBoolean(false);
			// time
			VarInt.writeVarInt(rnp, 0);
			// edition
			rnp.writeUByte(0);
			// rain level
			rnp.writeFloat(0);
			// lightning level
			rnp.writeFloat(0);
			// cheats enabled
			rnp.writeBoolean(true);
			// texture required
			rnp.writeBoolean(false);
			// level ID
			rnp.writeString("");
			// world name
			rnp.writeString("world");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		packet = rnp;
	}
}
```
VarInt is from Nukkit, but I changed that class to use Netty instead of whatever Nukkit uses.

BinaryUtils is also from Nukkit.

EDIT: Also, that packet is wrong (I changed some values and it broke and I forgot to test it...), so don't use it.

EDIT 2: Documented the class and fixed the issue, now it logs in! Based on this documentation: https://github.com/sel-project/sel-utils/blob/master/doc/pocket/100.md#play.start-game

EDIT 3: Also this fixed class doesn't crash MCW10 when logging in, yay!

**Comment by whirvis** [comment]
I believe I have fixed the issue! :)
Now version 2.4.6 will have this fix, be sure to download it!

**Comment by MrPowerGamerBR** [comment]
@MarfGamer tested connecting to my test server with MCW10 a few times and it seems the issue was fixed. (after all I didn't get disconnected when trying to connect a few times), thanks for fixing! 👍 😄 

PS: When you will start working on your MCPE server in Java? I'm curious because there isn't any good MCPE servers made in Java right now... (and I could help!)

**Comment by MarfGamer** [comment]
I do have one called [BeetRoot-MP](http://github.com/BeetRootMP) but all the changes to MCPE plus the current lagging multiplayer is making me consider on whether or not I should just wait until MCPE just uses TCP completely. When MCPE switches over to TCP completely, I will most likely leave this project for dead (But still fix bugs if any are found) as I will not need it anymore. The thing is, MCPE recently since 0.14 has seemed very laggy for basic things, along with other problems such as:

- All packets are sent at the end of ticks instead of immediately, causing noticeable lag even for chat
- The game uses XBOX Live instead of Mojang accounts (It was shoehorned in)
- Mojang removed the realms sections, meaning you know are forced to look at realms you have cancelled and making your already long list longer if you have alot of worlds or a lot of realms
- Mojang removed the cancel login button, meaning clients get locked when a server doesn't respond
- Mojang boasts cross-compatibility but in-reality it's just half-assed with versions ported over to different platforms (Windows 10, and even Apple TV). On top of this realms subscriptions cannot be managed unless you are on the same device type you purchased them on (For some retarded reason they don't just tie the subcription to the XBOX Live account)
- There is an ungodly amount of versions now when it used to just be PC, Mobile, and Mobile and Home Consoles
- The list goes on

**Comment by whirvis** [comment]
Also @MrPowerGamerBR I see you seem to be working on a server-software, would you like to join the BeetRoot-MP team? :)

**Comment by MrPowerGamerBR** [comment]
@MarfGamer well, I'm not very very very experienced with MCPE things, I could help, but only after the basic things are implemented (so, after at least chunk sending is implemented, because I can't figure out how to send chunk packets at all, and I already spent more than one week trying to do that but nope, MCPE doesn't like my chunk packets.)

**Comment by whirvis** [comment]
@MrPowerGamerBR Alright, I'll send you an invite :)

**Comment by robotman3000** [comment]
@MarfGamer I may have found the solution to this problem. In the `update` method of `RakNetSession` if the queue returned a null value `encapsulated.calculateSize()` would cause a NullPointerException disconnecting the client. I had a stack trace when I was debugging earlier but it was in the output of my IDE and I didn't think to save it.

**Comment by whirvis** [comment]
@robotman3000 Ah! I knew it had something to do with the RakNetSession, I'll look into it right away.

**Comment by whirvis** [comment]
After all this time, thanks to @robotman3000, I have found why when a client get's disconnected for an error the exception does not print. On line 697 of RakNetServer, when an exception is thrown the session is disconnected with no stack trace printed. I will immediately add a method to the server listener that will be called when a session causes an exception to be thrown. I will release this as version 2.5.0.
