### ISSUE TITLE
Please add support for more MTU values

### ISSUE THREAD

**Issue by robotman3000** [JRakNet/JRakNet#25]
The MCPE game uses the MTU 1492 but JRakNet doesn't support that MTU. The way I have fixed this for my own use is by adding `new MaximumTransferUnit(1492, 3)` to the list of units in `RakNetClient`. I put it as the first item in the array

**Comment by whirvis** [comment]
I can do that! :) Would something like this work?:

```java
RakNetClient client = new RakNetClient(); // Client
client.addMaximumTransferUnit(new MaximumTransferUnit(mtu, retries)); // New MTU

// Server connection code
```

**Comment by whirvis** [comment]
Added in version 2.5! The code example in the comment I made earlier is how you can do what you were asking for :)
