### ISSUE TITLE
Apollo, new project using JRakNet

### ISSUE THREAD

**Issue by NycuRO** [JRakNet/JRakNet#33]
Hi @MarfGamer .

I'm created one fork of Squidland, the latest project who used JRakNet because he is abandonated.

I want to invite you as collaborator for helping of RakNet :D 

I'm sending you one invitation, and i'm very happy if you can accept 👍

**Comment by MarfGamer** [comment]
Glad to accept! If you find any JRakNet glitches, feel free to let me know and I'll get to fixing them as fast as possible!

**Comment by NycuRO** [comment]
@MarfGamer Thanks so much! <3
