### ISSUE TITLE
How to catch NoFreeIncomingConnectionsException?

### ISSUE THREAD

**Issue by ghost** [JRakNet/JRakNet#56]
Hi, first off I'd like to thank you for this nifty library.

Whenever I'm connecting a client to a full server using the RakNetClient.connectThreaded(String) method a NoFreeIncomingConnectionsException is thrown. I'd like to catch it and recover by displaying a message to the user. This is my code (Client extends RakNetClient):
```
Client client = new Client();
try {
    client.connectThreaded("localhost", 44555);
} catch (Exception e) {
    System.err.println("Failed to connect, perhaps unknown host.");
}
```
How would I go about detecting this exception? Or better yet, is there an alternative way of detecting a full server?

Thank you in advance.

**Comment by ghost** [comment]
Alright, since no exception can be detected using RakNetClient.connectThreaded(String) I decided to run the connect(String) method in a separate thread and catch it there. The code above was replaced with the following and it now works:
```
Client client = new Client();
new Thread(new Runnable() {
    @Override public void run() {
        try {
            client.connect("localhost", 44555);
        } catch (Exception e) {
            System.err.println(e);
        }
    }
}).start();
```

**Comment by whirvis** [comment]
You ARE able to catch exceptions when on connectThreaded(). You need to utilize the onThreadException() method in the RakNetClientListener which is made to catch exceptions that were caught on the thread the client is running on.

**Comment by ghost** [comment]
Oh, that's very convenient, I'll use that method instead. Thank you!
