### ISSUE TITLE
Too many split packets

### ISSUE THREAD

**Issue by Creeperface01** [JRakNet/JRakNet#57]
I created simple proxy to connect to vanilla MCPE server, but if I try to connect server throws SplitQueueOverloadException 

https://hastebin.com/veciwanufe.vbs

**Comment by whirvis** [comment]
What version of MCPE are you using? The client should NOT be sending that many packets during login

**Comment by Creeperface01** [comment]
no, it was probably my fault, I connected the client to the server so I created an infinite loop

**Comment by Creeperface01** [comment]
can I ask one question? because I haven't found any raknet forum or community.
As I said Im trying to create simple proxy, with your raknet server and the foward packets to raknet client.
But it unfortunately doesn't work.

my simple [code](https://gist.github.com/Creeperface01/4509182820a62aec23faaabee221b44c)
