### ISSUE TITLE
Stop commiting doc changes when you havent actually changed it

### ISSUE THREAD

**Issue by TheDiamondYT1** [JRakNet/JRakNet#58]

**Comment by TheDiamondYT1** [comment]
Close this when you have read it, i would comment on a commit but its too long

**Comment by haxpor** [comment]
Good idea. Each commit is too long to read. Most of it is doc changes which is not the main attention point. The better is not to have doc committed at all polluting code changes.

Please allow me to give possible solutions here.
- Use `gh-pages` branch of Github to post only doc content to it so the project can still have free document hosted online. It could be of use to use [ghp-import](https://github.com/davisp/ghp-import) tool to automate thing further.
- Document content could be generate on-demand i.e. only when doing push on Github, or just do it every time the project has a new release either manually or through automated-script.

PS. JRakNet is great project.

**Comment by whirvis** [comment]
I will definitely look into this. I can see this annoying people now that I think about it. @TheDiamondYT1 Could you tell me what you were originally going to comment and on what commit you were going to post it on?

**Comment by TheDiamondYT1** [comment]
it was the most recent code update. Now i realise i couldve commented on the Update README commits, but oh well
