### ISSUE TITLE
How JRakNet works with RakNet?

### ISSUE THREAD

**Issue by shuizhihun** [JRakNet/JRakNet#60]
We're working on a game,The client of the game is developed in c++ and the server is developed in Java. We're going to use RakNet on the client side and use JRakNet on the server side, What we need to do to make it work? other Suggestions? Thanks!

**Comment by whirvis** [comment]
Just make sure you know how to use the JRakNet API and RakNet API, they both use the same exact protocol. Quick question, are you using the official C++ RakNet (Official) or CRakNet++ (My C++ implementation)? If you are using my C++ implementation, don't. It's nowhere near finished and can't even respond to pings yet :P However, JRakNet is fully capable of talking to the official RakNet.

Examples on how to use JRakNet can be found in the README.md file and in the "src/test/example" folder :)

**Comment by shuizhihun** [comment]
Thank you very much for your reply, This is very helpful to me.
