### ISSUE TITLE
What is the relationship between JRakNet and RakNet?

### ISSUE THREAD

**Issue by rulerzhang** [JRakNet/JRakNet#68]
I found that JRakNet Protocol Info is 8. But RakNet Protocol Info is 6.
What changes between Protocol 8 and Protocol 6? Thanks!

**Comment by rulerzhang** [comment]
I hope there's a C++ version for mobile games.

**Comment by whirvis** [comment]
Where are you getting that info from? It seems to be very outdated. Even then, this was meant for Minecraft: Pocket Edition and I believe Mojang might have bumped it for whatever reason but I'm not entirely sure. However, like stated in the README.md you can use this for whatever you want (including your own games) and should be able to use it with other games that support RakNet but I'm not entirely sure.

I am working on a C++ version called [CRakNet++](https://github.com/CRakNetPlusPlus/) but it is nowhere near finished.
