### ISSUE TITLE
Exception on client timeout

### ISSUE THREAD

**Issue by HoverEpic** [JRakNet/JRakNet#75]
Hi, is it possible to hide the Exception and call an abstract method onTimeout() for example.

```
com.whirvis.jraknet.session.TimeoutException: Session timeout
    at com.whirvis.jraknet.session.RakNetSession.update(RakNetSession.java:869)
    at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:814)
    at com.whirvis.jraknet.server.RakNetServer$1.run(RakNetServer.java:853)

```
https://github.com/JRakNet/JRakNet/blob/master/src/main/java/com/whirvis/jraknet/session/RakNetSession.java#L869

**Comment by whirvis** [comment]
That seems like a good idea. However, clients are not supposed to time out from their servers, hence the exception. Is there a reason why you cannot just use a try and catch block?

P.S. Did the interrupted exceptions from earlier go away in 2.9.2?

**Comment by HoverEpic** [comment]
Seems to be good for the interrupted exception =)

The timeout exception is thrown when a client crash/close game without disconnecting from the server.
The update() methode is called in your session thread cycle, I can't try catch this in my code (or i'm very tired and i didn't see how).

**Comment by whirvis** [comment]
"The timeout exception is thrown when a client crash/close game without disconnecting from the server." That means the client is throwing the exception correctly then, as it loses connection to the server and is unable to reestablish it. Lucky for you I have a method just for that in the ```RakNetClientListener```! Just override ```onThreadException(Throwable throwable)``` to handle exceptions on the client thread. By default, the method will just print the stack trace if it has not been overridden.

**Comment by HoverEpic** [comment]
Perfect, i'll try that in fiew days. Thank you.
