### ISSUE TITLE
How to send custom packet?

### ISSUE THREAD

**Issue by Frago9876543210** [JRakNet/JRakNet#76]
I want to send batch packet to client. How to do it?

**Comment by whirvis** [comment]
This has nothing to do with JRakNet and everything to do with Minecraft, please do some research on how the Minecraft client and server communicate with each other before simply opening an issue. I will not tell you how to send encode a batch packet to send to the client (as I do not know how), however I will tell you that you need to use the `sendMessage()` function in the `RakNetClientSession` class, which can be done after it has connected to the server.

I am sorry that the documentation for JRakNet is not very good, however I do not have much time on my hands get it where it should be :/ I'll try and write some better documentation and finish it so people can get started more easily with JRakNet. For now, I suggest you look around in the examples in the source code which show the code in action.

**Comment by Frago9876543210** [comment]
Could you provide an example? Suppose I have processed a client package, but how do I send an answer to it?

**Comment by Frago9876543210** [comment]
@Whirvis I'm trying to send data to the client, but its does not send answer
```java
package net.frago9876543210.server;

import com.whirvis.jraknet.RakNetException;
import com.whirvis.jraknet.RakNetPacket;
import com.whirvis.jraknet.identifier.MinecraftIdentifier;
import com.whirvis.jraknet.protocol.Reliability;
import com.whirvis.jraknet.server.RakNetServer;
import com.whirvis.jraknet.server.RakNetServerListener;
import com.whirvis.jraknet.session.RakNetClientSession;

import javax.xml.bind.DatatypeConverter;
import java.util.Random;

public class Main {
    public static void main(String[] args) {
        RakNetServer server = new RakNetServer(19132, 10,
                new MinecraftIdentifier("JRakNet Example Server", 201, "1.2.10", 0, 10,new Random().nextLong(), "New World", "Survival")
        );


        server.addListener(new RakNetServerListener() {
            @Override
            public void onClientConnect(RakNetClientSession session) {
                System.out.println(session.getAddress() + " connected");
            }

            @Override
            public void onClientDisconnect(RakNetClientSession session, String reason) {
                System.out.println(session.getAddress() + " disconnected");
            }

            @Override
            public void handleMessage(RakNetClientSession session, RakNetPacket packet, int channel) {
                System.out.println(DatatypeConverter.printHexBinary(packet.array()));
                session.sendMessage(Reliability.UNRELIABLE, new RakNetPacket(new byte[]{
                        (byte) 0xfe, (byte) 0x78, (byte) 0xda, (byte) 0x63,
                        (byte) 0x65, (byte) 0x62, (byte) 0x00, (byte) 0x02,
                        (byte) 0x00, (byte) 0x00, (byte) 0x2e, (byte) 0x00,
                        (byte) 0x08,
                }));
            }
        });

        try {
            server.start();
        } catch (RakNetException e) {
            e.printStackTrace();
        }
    }
}

**Comment by whirvis** [comment]
First of all, you are using the UNRELIABLE packet priority, meaning full well the client might not receive the message. Please use something of the RELIABLE type, such as RELIABLE_ORDERED. Second, just because you send data does not mean you will get a response. Many servers and clients in networking will just not respond to bad packets in order to save resources (As the person sending the bad packets might very well be doing so with malicious intent.)

Here's a link to some info on the current Minecraft protocol, it's up to date even with the betas of the game: https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol%20Documentation.md

**Comment by Frago9876543210** [comment]
I perfectly understand how the protocol works. And also tried all available reliability. However, the client does not send anything.

**Comment by whirvis** [comment]
The data you are sending looks like complete gibberish, the packet ID (The byte after 0xFE) does not look like it corresponds with any packet IDs what soever. What even are you trying to send to the client? Is the byte array compressed data?

**Comment by Frago9876543210** [comment]
0xFE is BatchPacket/WrapperPacket. It should be contained in an encapsulated package. 

https://github.com/pmmp/PocketMine-MP/blob/732b931556a26976dc5964fc47b49868da6cba1e/src/pocketmine/network/mcpe/protocol/BatchPacket.php#L69-L85

**Comment by whirvis** [comment]
That's what I thought. However, I'm not sure what you're actually trying to send with those compress bytes. What are the uncompressed bytes you are trying to send? Write them out in hex if you can, please.
P.S.: Is the client you are sending the messages to on the same machine as your server?

**Comment by Frago9876543210** [comment]
http://sandbox.onlinephpfunctions.com/code/474844029d82f3e2889ac0624fe662e575ba3d5d
050200000000
0x05 - len and after PlayStatusPacket

**Comment by whirvis** [comment]
You're sending the login packets in the wrong order then, I believe. Try sending a disconnect packet with your own custom message when the client connects and see how it responds. Once again, is the client that you are attempting to send data to on the same machine as your server?

**Comment by Frago9876543210** [comment]
> Once again, is the client that you are attempting to send data to on the same machine as your server?

Yes

**Comment by whirvis** [comment]
^ That is most likely your problem, Minecraft does not like servers that are on the same machine as it is (I can't do anything about this, you can thank Mojang and their shoddy client programming for this.) The only way you can test with Minecraft is if you have another machine to run the client or server on. I suggest using your mobile device since most phones can run Minecraft just fine. Once you have tested on another machine, let me know whether or not anything is working.

**Comment by Frago9876543210** [comment]
Nothing changed

**Comment by Frago9876543210** [comment]
![img](https://snag.gy/Ql4Edw.jpg)

**Comment by whirvis** [comment]
Alright, then do what I said earlier. Try sending a disconnect packet to the client.
