### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by portablestew** [JRakNet/JRakNet#77]
https://github.com/JRakNet/JRakNet/blob/ded512ff7af393d2e7de171ed03afe9adc9824f5/src/main/java/com/whirvis/jraknet/server/RakNetServer.java#L809

I'm seeing 100% CPU usage from a RakNetServer thread, while running a Minecraft DragonProxy (https://github.com/DragonetMC/DragonProxy). Without any sleep() or waitable signal here, I expect it spins pretty hard. 

I should add that the CPU usage drops dramatically after I log in with a user.

**Comment by whirvis** [comment]
I will fix this as soon as possible, thanks for the catch!

**Comment by whirvis** [comment]
The issue has now been fixed in version 2.9.3! Please update to it and let me know if the issue still persists so I can look into it more. Thank you! P.S.: I have removed the log warning that a sleep has been interrupted, as it seemed useless and seemed like it could be a nuisance.
