### ISSUE TITLE
RakNetClient.removeExternalServer() broken

### ISSUE THREAD

**Issue by whirvis** [JRakNet/JRakNet#86]
The ```removeExternalServer()``` method in ```RakNetClient``` does not work, as when checking if the server has actually been added before hand, it uses the ```contains()``` method rather than the ```containsKey()``` method, meaning that ```false``` will always be returned and as a result the rest of the function is never called.

**Comment by Whirvis** [comment]
Fixed in 2.9.6-SNAPSHOT.

**Comment by whirvis** [comment]
Fixed in version 2.9.6-SNAPSHOT, however I reopened this issue as the fix is not yet in an official release.

**Comment by whirvis** [comment]
Fixed in version 2.9.6
