### ISSUE TITLE
Normal communication can not be performed with BDS, LBSG Server, etc.

### ISSUE THREAD

**Issue by hmy2001** [JRakNet/JRakNet#98]
RakNetClient sending a NewIncoming Connection Packet with RELIABLE_ORDERED_WITH_ACK_RECEIPT will not start a session.
I confirmed it with the same server software as LBSG server and BDS
.

**Comment by hmy2001** [comment]
I suggest to don't use RELIABLE_ORDERED_WITH_ACK_RECEIPT.
Is it bad implement?

**Comment by whirvis** [comment]
I need more information than what you are handing me. I am not being given stack traces, only errors with hard to understand english. Please, provide a stack trace. I did find an error where the client was unable to connect to the LBSG server and fixed it accordingly, however, it had nothing to do with ConnectedPong.

**Comment by hmy2001** [comment]
Hmm, I will send you a Pull Request for fix because I can not explain well

**Comment by whirvis** [comment]
I am assuming that connection was not possible due to a crash at startup due to another issue. This issue has since been fixed, so I will close this issue and open another one to close to show that the issue had existed but has since been fixed.

**Comment by whirvis** [comment]
@hmy2001 As always, if the issues you have reported still exist, please let me know! I am always happy to help. The new version is now version 2.10.5, so make sure to update to that :)

**Comment by hmy2001** [comment]
No, this issue has not been fixed.

**Comment by hmy2001** [comment]
No, this issue has not been fixed.

**Comment by whirvis** [comment]
Alright, could you make a pull request then like you said you would?

**Comment by hmy2001** [comment]
I sent pull request.

**Comment by hmy2001** [comment]
The issue has been resolved!
