### ISSUE TITLE
About Connected Pong Packet

### ISSUE THREAD

**Issue by hmy2001** [JRakNet/JRakNet#99]
The timestapPong is not implemented in Connected Pong Packet in LBSG server because Decoding fails.
I suggest to check remaining packet buffer.

**Comment by whirvis** [comment]
What do you mean? When I send a ConnectedPing to the LBSG server, I simply get no response. I am not sure why this is the case, but I certainly get nothing back. Could you send me a stack trace of some sorts or more information? It's really hard to tell what you're needing when you give so little information.

**Comment by whirvis** [comment]
I have tested multiple other servers and have determined that is solely an LBSG issue, not a JRakNet issue. My basis for this is that I went around multiple server websites for MCPE and checked if the JRakNet client was able to connect to them and determine their latency. I did this for 10 servers and they all passed. However, I will state that I found a bug relating to maximum transfer units when doing this that has also been fixed.

**Comment by hmy2001** [comment]
![image](https://user-images.githubusercontent.com/7406613/46481891-53d0a180-c82f-11e8-9c61-f762f5a5047b.png)

**Comment by hmy2001** [comment]
I catched handle error exception.

**Comment by hmy2001** [comment]
The issue has been resolved!
